version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/jGrader/
hooks:
  ApplicationStop:
    - location: aws_scripts/stop.sh
  BeforeInstall:
    - location: aws_scripts/remove-old.sh
  AfterInstall:
    - location: aws_scripts/add-dependencies.sh
  ApplicationStart:
    - location: aws_scripts/start.sh
